### ISSUE TITLE
ReadMe

### ISSUE THREAD

**Issue by mackelito** [Countly/countly-sdk-cordova#1]
It would be nice to have an instruction on how to implement the script ;)

I'm trying out Appgyvers "Steroids" and would like to know what I need to include..

**Comment by osoner** [comment]
First wanted to send this :)

![](http://static.comicvine.com/uploads/original/11112/111123482/3581810-5080587534-Yup.%2B.jpg)

This is an SDK developed by a fellow community member and unfortunately not maintained by us at the moment. But if we push him enough I think he might want to write a README.

**Comment by mackelito** [comment]
Haha.. thx! :+1: 

I'll most likely fork this and make some changes.. right now it depends om jQuery and that might be something we can (should?) change?

**Comment by bmarker1** [comment]
+1  Not sure how to get this working.

**Comment by mackelito** [comment]
https://github.com/mackelito/countly-sdk-js

**Comment by osoner** [comment]
There are some modifications on the way. At least we have a readme now.

**Comment by CountlyAnalytics** [comment]
Please check this - https://github.com/nicolsondsouza/countly-sdk-js 

README file along with some improvements in codebase here will be merged to our main tree.

**Comment by nicolsondsouza** [comment]
The repo is updated with README file, also with offline cache,
Please report if there is any problem you may encounter.

**Comment by bmarker1** [comment]
Excellent! This helps tons.  I'm attempting to make this a 3.0+ plugin, I'll let you guys know if I get it working.

**Comment by nicolsondsouza** [comment]
This plugin will be made cordova 3.0 commandline compatible, which is in progress.

**Comment by nicolsondsouza** [comment]
The plugin has been made command line compatible but the source code doesn't support 3.0
If anyone knows what's wrong than please look here and could suggest https://github.com/nicolsondsouza/countly-sdk-js
It is the currently work in progress.
I am still trying to fix it.

**Comment by bmarker1** [comment]
I ran into the same issues.  After 3 days of trying to get this working, I've given up the fight.  I'm switching to GA, there's already a 3.0 plugin available and has custom events also... https://build.phonegap.com/plugins/297  No need to reinvent the wheel.
