### ISSUE TITLE
Hybrid Mobile app support : Ionic

### ISSUE THREAD

**Issue by YatinGrover** [Countly/countly-sdk-cordova#11]
I am developing a cross platform app using Ionic Framework and could't find any documentation for integrating countly push notification with angularjs/ionic/cordova.
There is very clear documentation for android and ios separately but same is missing for ionic. The example on github(phonegap example) doesn't run straightaway and the countly.js is lacking explanation on GCM integration.
Can you please provide some resources for implementing push notification in mobile apps created using ionic via countly.

**Comment by trinisofttechnologies** [comment]
Ok, will provide you a demo with ionic framework.

Thanks

**Comment by yarivdev** [comment]
A demo would be appreciated greatly.

**Comment by nicolsondsouza** [comment]
Ok, I can work on this Saturday, and get the ionic demo,

If that works for you?

**Comment by yarivdev** [comment]
Great. Thanks!

**Comment by trinisofttechnologies** [comment]
https://github.com/trinisofttechnologies/countly_ionic_example.git

Here is the sample application with proper documentation for ionic framework.

Thanks
