### ISSUE TITLE
Getting Thread 1: EXC_BAD_ACCESS ( code=1 address=0xc) error

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-cordova#12]
I am getting an error in the recordEvents function on the line NSString *data ( number 790 ) of countly.m
It only happens sometimes after a new install

Error

```
Thread 1: EXC_BAD_ACCESS ( code=1 address=0xc)
```

Function

```
(void)recordEvents:(NSString *)events
{
    NSString *data = [NSString stringWithFormat:@"app_key=%@&device_id=%@&timestamp=%ld&events=%@",
                      self.appKey,
                      [CountlyDeviceInfo udid],
                      time(NULL),
                      events];

    [[CountlyDB sharedInstance] addToQueue:data];

    [self tick];
}
```

The event object I was sending last

```
{"eventName":"view-home","eventCount":1,"segments":{"appcountry":"NZ","userId":"7233001","deviceId":"B396AAD6-7E92-48CD-8A88-A0E193D3CB99"}}
```

**Comment by trinisofttechnologies** [comment]
Ok, will take a look at it, and update you on this issue.

Thanks for letting us know about this issue.

**Comment by deliriousrhino** [comment]
Hi, any update about this issue? Our apps are still crashing because of this

**Comment by trinisofttechnologies** [comment]
A new update has been pushed,

This new update should fix this problem.

Note: It's a totally new revised version.

Re - open this issue again, if you think the problem persits.
