### ISSUE TITLE
New features for JS SDK

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#13]
JS SDK should honor the following items to support new Countly server related features
- [x] be able to set custom device ID upon initialization
- [x] be able to change deviceID at any time in the app (persistently save new device ID and continue using only that)
- [x] be able to change deviceID with data merge on server from old device ID using old_device_id api (http://resources.count.ly/docs/i#section-additional-parameters)
- [ ] report local user hour (0-23) together with timestamp (meaning with each request and in each event)
- [ ] report local user day of the week (0-sunday, 1 - monday, ... 6 - saturday) together with timestamp (meaning with each request and in each event)
- [x] Allow providing duration property in events
- [x] Allow to measure event duration, by implementing  eventStart(key), which will measure seconds internally until eventEnd(key, ..., other default event properties) is called
- [x] Report Views (webpages for webSDK, Activities for Android, etc) to provide an option to manually track views and an option to track them automatically, if platform supports it
- [x] Modify custom user properties through userdata subclass (to allow increment value, multiply value or store multiple values under the same key - array)
- [x] SDKs should follow HTTP redirection to make requests to Countly api servers
- [x] Allow sending metadata with each begin session request (http://resources.count.ly/docs/sdk-development-guide#section-sdk-meta-data)

**Comment by trinisofttechnologies** [comment]
ok,

We have this request, 
It's under development.

Thanks

**Comment by mymanga** [comment]
How soon can we get an update to this SDK seeing how it still has build errors

**Comment by gorkem-cetin** [comment]
@mymanga please create another issue and paste your build errors there. This issue is not related to build errors.

**Comment by trinisofttechnologies** [comment]
@mymanga sorry for the delay, I am working on this today, and should have the android version ready.

**Comment by trinisofttechnologies** [comment]
@mymanga I am assuming, that there is a build error on ios, There is an instruction on the build error, for ios, That's a known issue, and that's the only thing needs to be done manually, rest all is build and compiled automate by the sdk js.

**Comment by gorkem-cetin** [comment]
@erkanyildiz

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 
Picking this issue for android / iOS

Report Views (webpages for webSDK, Activities for Androind, etc) to provide an option to manually track views and an option to track them automatically, if platform supports it

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

Working on this issue

 Report Views (webpages for webSDK, Activities for Androind, etc) to provide an option to manually track views and an option to track them automatically, if platform supports it

Thanks

**Comment by gorkem-cetin** [comment]
Nicolson - I also added: 
- Allow sending metadata with each begin session request (http://resources.count.ly/docs/sdk-development-guide#section-sdk-meta-data)

**Comment by trinisofttechnologies** [comment]
"Report Views" is fixed,

Note: you will require java 1.8 in order to bundle the app.
java 1.7 will faile the auto build.

**Comment by gorkem-cetin** [comment]
Lets commit features we have, and make a release please :)

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

If the list is complete, 
We can cloes this issue.

Thanks

**Comment by gorkem-cetin** [comment]
It looks like there are still 3 items here to get done, can you check them ? If you think you are done, we can close.

**Comment by trinisofttechnologies** [comment]
ok

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

Please provide more info

"report local user hour (0-23) together with timestamp (meaning with each request and in each event)"

"report local user day of the week (0-sunday, 1 - monday, ... 6 - saturday) together with timestamp (meaning with each request and in each event)"

I do not see these method calls in both the sdks

Thanks

**Comment by gorkem-cetin** [comment]
We can remove them. I think it was planned but wasnt realized.

**Comment by trinisofttechnologies** [comment]
ok, so that means all the issues are completed.

So I can mark this issue as complete.

As the remaining issues are all fixed.

Thanks
