### ISSUE TITLE
ionic countly encounter "Couldn't store configuration in Countly Messaging"

### ISSUE THREAD

**Issue by horrylala** [Countly/countly-sdk-cordova#15]
1.i follow up the construction [https://github.com/trinisofttechnologies/countly_ionic_example](https://github.com/trinisofttechnologies/countly_ionic_example) ,but encountered some problems
1)Couldn't store configuration in Countly Messaging
2)i did not get google-play service and i don't  want and need push service ~

how should i do ?
i have push notification in my app .
in my AndroidManifest.xml

> ```
>     <service android:enabled="true" android:exported="false" android:icon="@drawable/logo" android:label="${package_name}" android:name=".tcp.service.SfPushService" android:process=":SfPushService" />
>     <receiver android:name=".service.reciver.TcpNotifyReceiver">
>         <intent-filter>
>             <action android:name="com_sf_tcp_network_action" />
>             <action android:name="com_sf_tcp_push_action" />
>         </intent-filter>
>     </receiver>
> ```

in my build.gradle

>   compile 'com.google.android.gms:play-services:9.4.0'

if i did not add this dependency ,it fails build

my error log

> 09-22 16:14:37.316 15066-15413/com.sf.sasp.debug E/MessagingAdapter: Couldn't store configuration in Countly Messaging
>                                                                      java.lang.reflect.InvocationTargetException
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at ly.count.android.sdk.MessagingAdapter.storeConfiguration(MessagingAdapter.java:40)
>                                                                          at ly.count.android.sdk.Countly.init(Countly.java:197)
>                                                                          at ly.count.android.sdk.CountlyCordova.execute(CountlyCordova.java:28)
>                                                                          at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
>                                                                          at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
>                                                                          at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
>                                                                          at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
>                                                                          at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
>                                                                          at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                          at android.os.Looper.loop(Looper.java:158)
>                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                                       Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
>                                                                          at android.content.res.Resources.getText(Resources.java:1468)
>                                                                          at android.content.res.Resources.getString(Resources.java:1564)
>                                                                          at android.content.Context.getString(Context.java:415)
>                                                                          at ly.count.android.sdk.messaging.CountlyMessaging.storeConfiguration(CountlyMessaging.java:142)
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at ly.count.android.sdk.MessagingAdapter.storeConfiguration(MessagingAdapter.java:40) 
>                                                                          at ly.count.android.sdk.Countly.init(Countly.java:197) 
>                                                                          at ly.count.android.sdk.CountlyCordova.execute(CountlyCordova.java:28) 
>                                                                          at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98) 
>                                                                          at org.apache.cordova.PluginManager.exec(PluginManager.java:133) 
>                                                                          at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59) 
>                                                                          at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
>                                                                          at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
>                                                                          at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                          at android.os.Looper.loop(Looper.java:158) 
>                                                                          at android.os.HandlerThread.run(HandlerThread.java:61) 
> 09-22 16:14:44.346 15066-15413/com.sf.sasp.debug W/GooglePlayServicesUtil: Cannot find Google Play services package name.
>                                                                            android.content.pm.PackageManager$NameNotFoundException: com.google.android.gms
>                                                                                at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:201)
>                                                                                at com.google.android.gms.internal.zzro.getPackageInfo(Unknown Source)
>                                                                                at com.google.android.gms.common.zze.zzby(Unknown Source)
>                                                                                at com.google.android.gms.common.zze.zzbx(Unknown Source)
>                                                                                at com.google.android.gms.common.zze.zzbs(Unknown Source)
>                                                                                at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
>                                                                                at com.google.android.gms.common.GooglePlayServicesUtil.isGooglePlayServicesAvailable(Unknown Source)
>                                                                                at ly.count.android.sdk.messaging.CountlyMessaging.checkPlayServices(CountlyMessaging.java:215)
>                                                                                at ly.count.android.sdk.messaging.CountlyMessaging.init(CountlyMessaging.java:126)
>                                                                                at java.lang.reflect.Method.invoke(Native Method)
>                                                                                at ly.count.android.sdk.MessagingAdapter.init(MessagingAdapter.java:27)
>                                                                                at ly.count.android.sdk.Countly.initMessaging(Countly.java:264)
>                                                                                at ly.count.android.sdk.Countly.initMessaging(Countly.java:248)
>                                                                                at ly.count.android.sdk.CountlyCordova.execute(CountlyCordova.java:131)
>                                                                                at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
>                                                                                at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
>                                                                                at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
>                                                                                at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
>                                                                                at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
>                                                                                at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
>                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                at android.os.Looper.loop(Looper.java:158)
>                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
> 09-22 16:14:48.806 15066-15413/com.sf.sasp.debug E/MessagingAdapter: Couldn't store configuration in Countly Messaging
>                                                                      java.lang.reflect.InvocationTargetException
>                                                                          at java.lang.reflect.Method.invoke(Native Method)
>                                                                          at ly.count.android.sdk.MessagingAdapter.storeConfiguration(MessagingAdapter.java:40)
>                                                                          at ly.count.android.sdk.Countly.initMessaging(Countly.java:271)
>                                                                          at ly.count.android.sdk.Countly.initMessaging(Countly.java:248)
>                                                                          at ly.count.android.sdk.CountlyCordova.execute(CountlyCordova.java:131)
>                                                                          at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
>                                                                          at org.apache.cordova.PluginManager.exec(PluginManager.java:133)
>                                                                          at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
>                                                                          at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
>                                                                          at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
>                                                                          at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39)
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                          at android.os.Looper.loop(Looper.java:158)
>                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)
>                                                                       Caused by: android.content.res.Resources$NotFoundException: String resource ID #0x0
>                                                                          at android.content.res.Resources.getText(Resources.java:1468)
>                                                                          at android.content.res.Resources.getString(Resources.java:1564)
>                                                                          at android.content.Context.getString(Context.java:415)
>                                                                          at ly.count.android.sdk.messaging.CountlyMessaging.storeConfiguration(CountlyMessaging.java:142)
>                                                                          at java.lang.reflect.Method.invoke(Native Method) 
>                                                                          at ly.count.android.sdk.MessagingAdapter.storeConfiguration(MessagingAdapter.java:40) 
>                                                                          at ly.count.android.sdk.Countly.initMessaging(Countly.java:271) 
>                                                                          at ly.count.android.sdk.Countly.initMessaging(Countly.java:248) 
>                                                                          at ly.count.android.sdk.CountlyCordova.execute(CountlyCordova.java:131) 
>                                                                          at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98) 
>                                                                          at org.apache.cordova.PluginManager.exec(PluginManager.java:133) 
>                                                                          at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59) 
>                                                                          at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41) 
>                                                                          at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method) 
>                                                                          at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:39) 
>                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                          at android.os.Looper.loop(Looper.java:158) 
>                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by trinisofttechnologies** [comment]
Hi Horrylala I am looking into this issue.

Thanks

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin We will need to make countly push in another branch and countly analytics in another branch.

**Comment by gorkem-cetin** [comment]
No problem with that, we can do it.

**Comment by trinisofttechnologies** [comment]
Note: This request is in implementation.

**Comment by trinisofttechnologies** [comment]
Note, master branch only contains core countly features.
Push is now moved in "push" branch.

Thanks
