### ISSUE TITLE
Using countly-sdk-js with ionic

### ISSUE THREAD

**Issue by TonyWang8904** [Countly/countly-sdk-cordova#16]
Hi, I am using countly-sdk-js with ionic, and I have been successfully ran your demo app. Ionic works wth AngularJS and  I want to use countly in each controller to send event, but console error : ReferenceError: Countly is not defined.
I want to know how to using countly-sdk-js in angularjs Dependency injection. 
Demo code
`.controller('DashCtrl', function($scope) {
  Countly.init("http://172.28.112.102","16be70383b9d4af3e87f81b4de318b53e5d3ecd4");
  var events = {"eventName":"event_segment_sum","eventCount":1,"eventSum":"0.99"};
  events.segments = {"Country" : "Turkey", "Age" : "28"};
  Countly.sendEvent(events);
})`

**Comment by trinisofttechnologies** [comment]
@TonyWang8904

I see,
in this case you may wanna add the countly.js file manually

``` html
<script type="text/javascript" src="Countly.js"></script>
```

put the above tag in html and 
put Countly.js file in your www directory.
https://github.com/Countly/countly-sdk-js/blob/master/Countly.js

Thanks
