### ISSUE TITLE
SDK meta data

### ISSUE THREAD

**Issue by erkanyildiz** [Countly/countly-sdk-cordova#20]
Request coming through JS SDK needs to send its own SDK meta data (version and name) for both iOS and Android.

Please edit these lines as below:
`2.2` (or `2.2.1` if you plan to make a new release)
`js-cordova-ios`

iOS
https://github.com/Countly/countly-sdk-js/blob/master/src/ios/sdk/CountlyCommon.m#L19
https://github.com/Countly/countly-sdk-js/blob/master/src/ios/sdk/CountlyCommon.m#L20

Android
https://github.com/Countly/countly-sdk-js/blob/master/src/android/Countly.java#L52
https://github.com/Countly/countly-sdk-js/blob/master/src/android/Countly.java#L56

Until we come up with a better solution, manually overriding these values for each JS SDK release is ok.

**Comment by erkanyildiz** [comment]
@trinisofttechnologies any progress with this one?

**Comment by trinisofttechnologies** [comment]
Ohh, @erkanyildiz 

This issue was never assigned to me.

@gorkem-cetin 
Please assign this issue to me.
I am unable to assing this issue to myself.

**Comment by gorkem-cetin** [comment]
Assigned.

**Comment by trinisofttechnologies** [comment]
This changes are merged with dev-trinisoft branch

Will merge with master when we will make a release.

Thanks

**Comment by erkanyildiz** [comment]
Neither on `master` nor on `dev-trinisoft` branch, SDK meta data is not updated as I specified.

**Comment by trinisofttechnologies** [comment]
ok, working on it.

**Comment by trinisofttechnologies** [comment]
Now get it.

This is fixed in this commit.

1f5d04088f8e03548d6f0ad3f94b57ef83926100
