### ISSUE TITLE
addCrashLog missing in Countly.js

### ISSUE THREAD

**Issue by kwv** [Countly/countly-sdk-cordova#21]
The [documentation ](http://resources.count.ly/v1.0/docs/phonegap-icenium-meteor#section-crash-reporting) refers to manually adding crash log:
```
// Send a custom crash log
Countly.addCrashLog("My crash log from JavaScript");
```

This API does not appear to be implemented (yet?) in [Countly.js](https://github.com/Countly/countly-sdk-js/blob/master/Countly.js).   

Is the intent of the API for application managed non-fatal errors (e.g. gracefully caught 500 responses)? 

From tracing through the Android code, its not clear if [this](https://github.com/Countly/countly-sdk-js/blob/master/src/android/Countly.java#L803-L806) *should* be exposed.  I didn't spend a lot of time, but I couldn't find what sends the `CrashDetails` generated in `addCrashLog`

Rather should [logException](https://github.com/Countly/countly-sdk-js/blob/master/src/android/Countly.java#L812-L818) be overloaded to take a string?   That might make more sense to expose as `addCrashLog` in Countly.js?

**Comment by trinisofttechnologies** [comment]
I will check again on master branch.

**Comment by trinisofttechnologies** [comment]
@kwv 

Sorry, I checked it, and seems like this method wasn't implemented.

I have added the method now, in this 550fefb12f38f594cda78ce527e380be2c219495 commit.

Thanks
