### ISSUE TITLE
SDK does not honor Countly.messagingMode.TEST when initializing messaging

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#22]
Android devices are treated as production devices, even though marking them as “Countly.messagingMode.TEST” when initializing messaging inside app.

**Comment by trinisofttechnologies** [comment]
ok

**Comment by trinisofttechnologies** [comment]
Test on android, now shows production device token
Test on iOS code confirmed, and device token shows up but not actual test.
