### ISSUE TITLE
Update SDK to support latest Ionic + Cordova

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#24]

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

The latest cordova version is 6.x and it is supported by this sdk,

The future release of cordova is 7.x which isn't release yet.
So we wait until it is released and then work on the sdk, to avoid unwanted work.

**Comment by gorkem-cetin** [comment]
Makes sense, thank you.

**Comment by trinisofttechnologies** [comment]
Oh sorry It is released, as of 04 May 2017.

Will review the required changes and update the change.

**Comment by gorkem-cetin** [comment]
OK :)

**Comment by trinisofttechnologies** [comment]
A test was conducted for latest cordova version: 7.0.1

And it behaves properly.

ionic.countly.ts is added for ionic 2.0 supported
