### ISSUE TITLE
EndEvent doesn't send Segmentation

### ISSUE THREAD

**Issue by CDann3r** [Countly/countly-sdk-cordova#26]
Events that are created with startEvent("Event") and ended with additional information via endEvent({eventName:"Event",countCount:1,segments:{...}}) will not be sent completely to the countly server.

**Comment by CDann3r** [comment]
I already found the solution to this problem in the countly.js

The code part that determines the eventType is not setting all possible Types:
Original code within Countly.endEvent():

    if(options.segments && options.eventSum)
        eventType = "eventWithSumSegment";

This code should be enriched with the other event types like:


    if(options.segments && options.eventSum)
        eventType = "eventWithSumSegment";
    else if(options.segments)
        eventType = "eventWithSegment";
    else if(options.eventSum)
        eventType = "eventWithSum";

**Comment by CDann3r** [comment]
my bad... I used the version 2.2.0 that is published on https://www.npmjs.com/package/cordova-plugin-countly

**Comment by CDann3r** [comment]
sorry for the confusion... the Method sendEvent has the right differentiation regarding the event type but endEvent does not... This fix still needs to be supplied.

**Comment by CDann3r** [comment]
Countly.sendEvent = function(options){
    var args = [];
    var eventType = "event"; //event, eventWithSum, eventWithSegment, eventWithSumSegment
    var segments = {};

    if(options.eventSum)
        eventType = "eventWithSum";
    if(options.segments)
        eventType = "eventWithSegment";
    if(options.segments && options.eventSum)
        eventType = "eventWithSumSegment";


Countly.endEvent = function(options){
    if(typeof options === "string")
        options = {eventName: options};
    var args = [];
    var eventType = "event"; //event, eventWithSum, eventWithSegment, eventWithSumSegment
    var segments = {};

    if(options.segments && options.eventSum)
        eventType = "eventWithSumSegment";

**Comment by trinisofttechnologies** [comment]
@CDann3r Thanks for the update, I will check with @gorkem-cetin 

And see how to is this supported with other sdks.

Thanks

**Comment by trinisofttechnologies** [comment]
ok, I am working on this issue, will report on this by tomorrow.

**Comment by CDann3r** [comment]
Hi, please check the following Pull Request.
https://github.com/Countly/countly-sdk-js/pull/27
Thanks

**Comment by trinisofttechnologies** [comment]
Ok

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

This issue is stil pending. 

As the pull request didn't had the change I was expecting.

**Comment by trinisofttechnologies** [comment]
in progress

**Comment by trinisofttechnologies** [comment]
android in testing mode

**Comment by trinisofttechnologies** [comment]
Please look at this documentation for start and end event with custom segmentation.

https://resources.count.ly/v1.0/docs/phonegap-icenium-meteor#section-custom-events

Thanks
