### ISSUE TITLE
Don’t receive push notifications on iOS with Cordova SDK 

### ISSUE THREAD

**Issue by amialkumau** [Countly/countly-sdk-cordova#28]
We've got a problem with receiving iOS push notifications(We work with Cordova SDK). We set APN Auth key and after that we initialize device, receive registration id from APN, but still can't' receive notifications on device.

Commands we used:
```
Countly.init("https://us-try.count.ly","our_app_key");
Countly.initMessaging({"messageMode": Countly.messagingMode.PRODUCTION, "projectId": "gcm_id"})
Countly.start();
var push = PushNotification.init({
    android: {
        senderID: "gcm_id"
    },
    ios: {
        alert: "true",
        badge: "true",
        sound: "true"
    }
});
push.on('registration', function(data) {
    Countly.onRegistrationId({
        "registrationId": data.registrationId,
        "mode": Countly.messagingMode.PRODUCTION,
        "projectId": "gcm_id"
    })

   console.log(data.registrationId) // here we get registrationId
});
```
On dashboard we have something like this:
![123](https://user-images.githubusercontent.com/15383558/35799318-5ff5c76e-0a76-11e8-9630-b8b1407ce66c.png)

We can create notification from our app, but can't receive them!

**Comment by gorkem-cetin** [comment]
Can you try to clear your cache and refresh page again? There seems to be an issue description there but somehow it is not viewed. Thanks!

**Comment by nicolsondsouza** [comment]
@BigBlackAndWhitePanda 

This issue is being worked on.

**Comment by nicolsondsouza** [comment]
@BigBlackAndWhitePanda For me it is still working.

I will make a video recording on the same, and put that on a drive so that you can follow it and get the push implemented.

Thanks

**Comment by nicolsondsouza** [comment]
https://drive.google.com/open?id=1xJnuWUw5DCY_KEVVQIb2oHNV7BhclK62

Please see the above link.

Closing this issue, as it is working correctly as expected.

Thanks
