### ISSUE TITLE
Device & OS version not sent correctly

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#29]
OS version and device name cannot be sent (eg Galaxy S7, Android 8.1., iphone 7, iOS 11)

**Comment by Michenux** [comment]
Just made a new test. It is working with the countly-sdk-js.

The issue is when using the cordova-sdk-web inside a cordova application.

**Comment by trinisofttechnologies** [comment]
@michenux

That explains the situation.

cordova sdk web is only for browser.

There detailing on the phone is not available unless you have native access.

You can consider shifting to countly-sdk-js

As it is a better version / control over analytics on it.

Thanks
