### ISSUE TITLE
Not using any native code

### ISSUE THREAD

**Issue by mkutscher** [Countly/countly-sdk-cordova#3]
Hello,

it looks like the countly.js is not using any native code - everything is done in plain javascript. So why we need to use the native sdks? Also is the native OpenUDID never used.

Am I missing something or is the native code unnecessarily?

**Comment by nicolsondsouza** [comment]
When I added the plugin in the app without native sdk, It didn't worked for android and iOS,
And when I added native sdk  it, it started working.
So that's why in the tutorial I have added the description to put the sdk.

Have you tried without the sdk?
Is it working for you?

**Comment by nicolsondsouza** [comment]
Please reopen this issue, 
if you are finding the countly.js working as standalone,
Also let us know if we can help you with Countly.
