### ISSUE TITLE
Enable javascript error logging

### ISSUE THREAD

**Issue by Michenux** [Countly/countly-sdk-cordova#30]
Hi,

I would like to be able to log javascript errors with the Cordova Countly JS SDK.

A quick-win would be to add a Countly.log_error(string) method.
And we will use it like this :
Countly.log_error(JSON.stringify(err));

U can have a look at the cordova countly web sdk too :
[recordError](https://github.com/Countly/countly-sdk-web/blob/2f7e4ffbd5b17a7422a7a9bcfb2830d299f69572/lib/countly.js#L1385)
You can tell if it is a fatal or non-fatal crash, and add segments on the error.
It seems to handle the format of the error (string/object, stack, ...).

They also have added a feature to capture globally all javascript errors :
[track_errors](https://github.com/Countly/countly-sdk-web/blob/2f7e4ffbd5b17a7422a7a9bcfb2830d299f69572/lib/countly.js#L504)

**Comment by trinisofttechnologies** [comment]
@Michenux 

As per the latest master branch this issue is fixed.

app.addCrashLog = function(){
        Countly.addCrashLog("User Performed Step A");
        setTimeout(function(){
            Countly.addCrashLog("User Performed Step B");
        },1000);
        setTimeout(function(){
            Countly.addCrashLog("User Performed Step C");
            console.log("Opps found and error");
            Countly.logException("My Customized error message");
        },1000);

    }

Here is the documentation of usage.

This is also updated here:

https://resources.count.ly/v1.0/docs/phonegap-icenium-meteor#section-crash-reporting

**Comment by Michenux** [comment]
About logging an Error object, i have used this :

```
function replaceErrors(key, value) {
    if (value instanceof Error) {
        var error = {};

        Object.getOwnPropertyNames(value).forEach(function (key) {
            error[key] = value[key];
        });

        return error;
    }

    return value;
}

var error = new Error('testing');
error.detail = 'foo bar';

Countly.logException(JSON.stringify(error, replaceErrors));
```
In the web interface, i get the following. Not perfect because i don't care about the java stackstrace, i only care about the JS stack.

![image](https://user-images.githubusercontent.com/650789/37037519-c282e720-2152-11e8-9aed-34117bda0b71.png)

Do you think you can improve that ?

**Comment by trinisofttechnologies** [comment]
Yes, I will look into it.

Yes we can improve that.

**Comment by Michenux** [comment]
Any news ?

**Comment by trinisofttechnologies** [comment]
in progress

**Comment by trinisofttechnologies** [comment]
This issue is fixed and documentation is updated.

Please review the documentation before implementing the latest version.

You will need to add stacktrace.js manually as per example here:

https://github.com/Countly/countly-sdk-js/blob/master/index.html#L61

Let me know if there is anything more to be added.

Thanks
