### ISSUE TITLE
No example for ionic 3

### ISSUE THREAD

**Issue by canercanbaz** [Countly/countly-sdk-cordova#32]
Hi,

I would like to use your services like push notifications for my ionic 3 project. However, I could not find any concrete example using Countly on the web. Could you please provide an example for Ionic 3 if you have any chance to do so? Thank you in advance.

**Comment by trinisofttechnologies** [comment]
Ok, I will review ionic 3.0 framework and provide with a demo / time estimation on completing this issue.

Thanks

**Comment by canercanbaz** [comment]
Thanks for the immediate reply. I am looking forward to have a demo from you.

**Comment by trinisofttechnologies** [comment]
Hi @canercanbaz 

Here is an example for ionic 2.0, which is same for the ionic 3.0

https://github.com/trinisofttechnologies/countly-demo-ionic-2.0

Thanks

**Comment by canercanbaz** [comment]
I successfully established the connection between the application and the dashboard. I can see 1 online user etc. However, I cannot send a push notification to my app. It says there is no push-enabled user.

**Comment by gorkem-cetin** [comment]
I think you enabled push and then your token is sent right? Make sure to let us know all the steps you did.

**Comment by canercanbaz** [comment]
I enabled the push finally. However, when I sent the push notification it says 

GCM 200 message error
(MismatchSenderId)

Most probably Countly competes for tokens with other GCM / Firebase SDK you have in your app. Please override the way Countly or another SDK get a token so they would end up using the same token.

I can't get this work.

**Comment by gorkem-cetin** [comment]
Caner, please make sure you have read this and let us know if / when you did, and whether it works or not after you have taken all necessary precautions (eg make sure you don't have another SDK in your app that causes this).

`Most probably Countly competes for tokens with other GCM / Firebase SDK you have in your app. Please override the way Countly or another SDK get a token so they would end up using the same token.`

**Comment by trinisofttechnologies** [comment]
Hi,

I am running this on my own mac

And trying to make a tutorial video.

However you should make a new issue.

As this issue says ionic 3.0 demo.

Future users would also like to get an idea over this.

Note: I haven't got any success yet, so I am still trying to assemble all the pieces on FCM.

Thanks

**Comment by canercanbaz** [comment]
Hi again, did you get it running? Thanks
