### ISSUE TITLE
GCM 200 message (MismatchSenderId) Push Notification

### ISSUE THREAD

**Issue by canercanbaz** [Countly/countly-sdk-cordova#33]
Hi, I could not get over this issue for a couple of days. It says it sends push notification successfully. However, when I go and see the details of the sent message. It says:

> Most probably Countly competes for tokens with other GCM / Firebase SDK you have in your app. Please override the way Countly or another SDK get a token so they would end up using the same token.

I need Countly for push notification facility, but I can't use or set it up correctly.

**Comment by gorkem-cetin** [comment]
@canercanbaz is this issue still ongoing? Did you check the given message ?

**Comment by canercanbaz** [comment]
Yes, it still exists. The thing is my trial account is about to expire and I can't even try the push notification facility of Countly.

**Comment by gorkem-cetin** [comment]
As per the message, do you have any other SDKs that competes with Countly SDK?

**Comment by gorkem-cetin** [comment]
Closing this issue but please reopen if you think you dont have another SDK that competes with Countly SDK.
