### ISSUE TITLE
Unable to load PlatformApi from platform. Error: Cannot find module 

### ISSUE THREAD

**Issue by Michenux** [Countly/countly-sdk-cordova#39]
Hi,

I think something is not correct in the build process when i use this plugin.

First, my environnement:
cordova 8.1.2
cordova ios 4.5.5

I have created a cordova project and i have added the plugin with the command in the documentation.
````
cordova plugin add https://github.com/Countly/countly-sdk-js.git
````
** In package.json:
Dependencies: 
```
"countly-sdk-js.git": "https://github.com/Countly/countly-sdk-js.git"
```
Cordova part:
```
"ly.count.cordova": {}
```

** In config.xml 
```
<plugin name="ly.count.cordova" spec="https://github.com/Countly/countly-sdk-js.git" />
```

When in run "cordova platform add ios@4.5.5", it works but i got the plugin twice (in deps) in package.json :
```
"countly-sdk-js": "git+https://github.com/Countly/countly-sdk-js.git",
"ly.count.cordova": "https://github.com/Countly/countly-sdk-js.git"
```

Then, i delete my package-lock.json and rerun npm install to get a new one that matches the last updates of the file.

Then, i run "npm ci" (it deletes the node_modules, checks that all is correct between package.json and package-lock.json) but i got the error :
```
npm ERR! Missing: ly.count.cordova@https://github.com/Countly/countly-sdk-js.git
```

If i remove the ly.count.cordova from package.json (in deps), delete package-lock.json, rerun npm install, then "npm ci" works.

Then, i delete platforms and plugin directories, and rerun the command:
```
cordova platform add ios
```
I got the error:
```
Using cordova-fetch for cordova-ios@^4.5.5
Adding countly-sdk-js project...
Unable to load PlatformApi from platform. Error: Cannot find module '/private/tmp/test/AppTest/node_modules/countly-sdk-js'
Unhandled "error" event. (The platform "countly-sdk-js" does not appear to be a valid cordova platform. It is missing API.js. countly-sdk-js not supported.)
```

My opinion:
You should republish a npm package with a unique name cordova-plugin-countly and the same for the plugin id.
Having two different names is a problem for strong industrialisation : ly.count.cordova and countly-sdk-js

**Comment by trinisofttechnologies** [comment]
Ok, I will try to emulate your steps and see from a fresh user.

Where things may be wrong.

Also yeah, will look into the naming convention as it's different.

Thanks for the issue.

**Comment by trinisofttechnologies** [comment]
Ok, changed 2 different naming convention into one.

Changes can be reviewed here.

https://github.com/Countly/countly-sdk-js/commit/2fbe2054bb8cf9587f6b8b1fbcc79ab31ae8bd70

@Michenux 

Thanks for your view point on the naming convention.

As we are using countly-sdk-js mostly all over the places,

I have replaced ly.count.cordova to countly-sdk-js

Let me know if there is any more trouble / changes you might need.

Please re-open this issue and comment, if you feel, your issue is handled properly.

**Comment by Michenux** [comment]
This is great for the naming convention but it did not resolve the error.

```
$ cordova create testcordova com.mycompany.testcordova testcordova
$ cd testcordova
$ cordova platform add ios
$ cordova plugin add https://github.com/Countly/countly-sdk-js.git
```

Everything is fine at the moment.
Now :

```
$ rm -rf node_modules platforms plugins
$ npm ci
$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.5
Adding countly-sdk-js project...
Unable to load PlatformApi from platform. Error: Cannot find module '/Users/lmichenaud/Desktop/testcordova/testcordova/node_modules/countly-sdk-js'
Unhandled "error" event. (The platform "countly-sdk-js" does not appear to be a valid cordova platform. It is missing API.js. countly-sdk-js not supported.)
````

Can u reproduce the same ?

**Comment by trinisofttechnologies** [comment]
ok, I couldn't reproduce the issue on the first try.


I will follow your steps, and confirm on the problem.

**Comment by trinisofttechnologies** [comment]
log 1
[take2]$ cordova create testcordova com.mycompany.testcordova testcordova
Creating a new cordova project.
[take2]$ cd testcordova
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
cordova plugin add https://github.com/Countly/countly-sdk-js.git
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mycompany.testcordova
	Name: testcordova
iOS project created with cordova-ios@4.5.5
rm -rf node_modules platforms pluginsDiscovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project

Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
[testcordova]$ cordova plugin add https://github.com/Countly/countly-sdk-js.git
rm -rf node_modules platforms plugins
Installing "countly-sdk-js" for ios
Adding countly-sdk-js to package.json
Saved plugin info for "countly-sdk-js" to config.xml
[testcordova]$ rm -rf node_modules platforms plugins
[testcordova]$ npm install
npm WARN com.mycompany.testcordova@1.0.0 No repository field.

added 45 packages in 17.627s
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.5
Failed to fetch platform cordova-ios@^4.5.5
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mycompany.testcordova
	Name: testcordova
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "countly-sdk-js" in config.xml. Adding it to the project
Installing "countly-sdk-js" for ios
Adding countly-sdk-js to package.json
Saved plugin info for "countly-sdk-js" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
[testcordova]$ cordova run ios
Building for iPhone X Simulator
Building project: /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/testcordova.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

No target specified for emulator. Deploying to iPhone-X, 12.1 simulator
/Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/emulator/testcordova.app/Info.plist file not found.

**Comment by trinisofttechnologies** [comment]
[take2]$ cordova create testcordova com.mycompany.testcordova testcordova
Creating a new cordova project.
[take2]$ cd testcordova
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@~4.5.4
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mycompany.testcordova
	Name: testcordova
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
[testcordova]$ cordova plugin add https://github.com/Countly/countly-sdk-js.git
Installing "countly-sdk-js" for ios
Adding countly-sdk-js to package.json
Saved plugin info for "countly-sdk-js" to config.xml
[testcordova]$ rm -rf node_modules platforms plugins
[testcordova]$ npm install
npm WARN com.mycompany.testcordova@1.0.0 No repository field.

added 45 packages in 18.164s
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.5
Failed to fetch platform cordova-ios@^4.5.5
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
Failed to get absolute path to installed module
[testcordova]$ cordova platform add ios
Using cordova-fetch for cordova-ios@^4.5.5
Adding ios project...
Creating Cordova project for the iOS platform:
	Path: platforms/ios
	Package: com.mycompany.testcordova
	Name: testcordova
iOS project created with cordova-ios@4.5.5
Discovered plugin "cordova-plugin-whitelist" in config.xml. Adding it to the project
Installing "cordova-plugin-whitelist" for ios
Adding cordova-plugin-whitelist to package.json
Saved plugin info for "cordova-plugin-whitelist" to config.xml
Discovered plugin "countly-sdk-js" in config.xml. Adding it to the project
Installing "countly-sdk-js" for ios
Adding countly-sdk-js to package.json
Saved plugin info for "countly-sdk-js" to config.xml
--save flag or autosave detected
Saving ios@~4.5.5 into config.xml file ...
[testcordova]$ cordova run ios
Building for iPhone X Simulator
Building project: /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/testcordova.xcworkspace
	Configuration: Debug
	Platform: emulator
Build settings from command line:
    CONFIGURATION_BUILD_DIR = /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/emulator
    SDKROOT = iphonesimulator12.1
    SHARED_PRECOMPS_DIR = /Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/sharedpch

Build settings from configuration file '/Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/cordova/build-debug.xcconfig':
    CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES = YES
    CODE_SIGN_ENTITLEMENTS = $(PROJECT_DIR)/$(PROJECT_NAME)/Entitlements-$(CONFIGURATION).plist
    CODE_SIGN_IDENTITY = iPhone Developer
    ENABLE_BITCODE = NO
    GCC_PREPROCESSOR_DEFINITIONS = DEBUG=1
    HEADER_SEARCH_PATHS = "$(TARGET_BUILD_DIR)/usr/local/lib/include" "$(OBJROOT)/UninstalledProducts/include" "$(OBJROOT)/UninstalledProducts/$(PLATFORM_NAME)/include" "$(BUILT_PRODUCTS_DIR)"
    OTHER_LDFLAGS = -ObjC
    SWIFT_OBJC_BRIDGING_HEADER = $(PROJECT_DIR)/$(PROJECT_NAME)/Bridging-Header.h

No target specified for emulator. Deploying to iPhone-X, 12.1 simulator
/Users/trinisoft/office/countly/app/take2/testcordova/platforms/ios/build/emulator/testcordova.app/Info.plist file not found.

**Comment by trinisofttechnologies** [comment]
@Michenux 

Please review the log above,

I am not getting the same error,

I am using mac, with cordova, and iOS version same as you.

**Comment by trinisofttechnologies** [comment]
BTW, you shouldn't remove the plugins folder.

But in my example, even if I did, there wasn't any problem with it.

So, something might be wrong in your platform.

Can you give me more precise details on your platform, 

so that I can try on those specific variant.

OS: macOS
version: Mojave
cordova: I have it.
ios: I have it.

node -v
v9.5.0

npm -v
5.6.0

and anything that you can add.

Thanks

**Comment by Michenux** [comment]
OS: mac OS Mojave
cordova 8.1.2
node 10.13.0
npm 6.4.1

I have tried with node 8.9.4 and i reproduce the same error as you : 
```
cordova platform add ios                                                                                                                                 [ruby-2.5.1]
Using cordova-fetch for cordova-ios@^4.5.5
Failed to fetch platform cordova-ios@^4.5.5
Probably this is either a connection problem, or platform spec is incorrect.
Check your connection and platform name/version/URL.
```

"Probably this is either a connection problem, or platform spec is incorrect." -> i think it is not a connection problem but a platform spec problem.
And i think the root cause is the same, it is just that the error message is not the same between node 8.9.5/npm-5.6.0 and node 10.13.10/npm-6.4.1

**Comment by trinisofttechnologies** [comment]
Yes, it is true.

It is related to npm / nodejs.

And for me it still works.

So hoping that is not a error from the plugin,

but something to do in the platform.

The official way to add cordova plugins is:

cordova plugin add this_plugin

npm install isn't the official way, but works!!

Let me know, if there requires my input / discussion.

I will be happy to help!

**Comment by Michenux** [comment]
The fact is that i have only the problem with this cordova plugin.

**Comment by trinisofttechnologies** [comment]
I see, I will review on this with latest npm version and try to emulate the problem.

Yeah, as we have to support the latest version.
