### ISSUE TITLE
How to send an event with segmentation?

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-cordova#4]
Thanks for the plugin. How can I send events with segmentation

Like the example here
http://resources.count.ly/v1.0/docs/custom-events

**Comment by nicolsondsouza** [comment]
That isn't implemented yet,
It sends just the basic events now.

will implement segmentation.

**Comment by nicolsondsouza** [comment]
@deliriousrhino

implemented android,
working on ios
If you are in hurry, you may pull it from this repo,
https://github.com/nicolsondsouza/countly-sdk-js.git

**Comment by nicolsondsouza** [comment]
implemented ios,
docs in index.html file,
testing events.

**Comment by deliriousrhino** [comment]
Thanks for the quick turn around I will put and test

**Comment by nicolsondsouza** [comment]
android tested and working good.
testing ios.

**Comment by nicolsondsouza** [comment]
Tested on ios, working fine.

closing this issue.
