### ISSUE TITLE
Implement Ratings & Feedbacks

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#40]
For more information: 

https://count.ly/plugins/ratings-and-feedback

https://resources.count.ly/docs/sdk-development-guide#section-star-rating

**Comment by trinisofttechnologies** [comment]
working on it.

**Comment by trinisofttechnologies** [comment]
![screenshot 2019-02-06 at 6 03 02 pm](https://user-images.githubusercontent.com/10754117/52341763-7cfd7a80-2a39-11e9-80ac-fb04ee8d161a.png)
Rating modal in progress.

**Comment by andreialecu** [comment]
I'm just trying this plugin, the readme said to use this github repo as the source of the plugin.

Seeing this error, I assume it's because of the work being done here:

![image](https://user-images.githubusercontent.com/697707/52366184-c78af100-2a51-11e9-9788-e34ee036bc3c.png)

There's no such element so the entire app fails to load.

**Comment by trinisofttechnologies** [comment]
Oops sorry, I should have pushed to dev branch.

This is fixed and pushed.

**Comment by trinisofttechnologies** [comment]
Rating UI, and JS implementation fixed and pushed to master branch.

Working on Feedback implementation.

**Comment by trinisofttechnologies** [comment]
@andreialecu, sorry for pushing into wrong branch.

Please update the plugin and it should work.

**Comment by trinisofttechnologies** [comment]
working on feedback modal.

**Comment by baptisteArno** [comment]
I'd like to implement this plugin on my Ionic (Cordova) app. I want to use the default widget with  styled components : 
![image](https://user-images.githubusercontent.com/16015833/58241433-4845d280-7d4d-11e9-9e6c-005055b55bdf.png)
Is this possible ?

**Comment by baptisteArno** [comment]
@trinisofttechnologies I implemented it on my own. It uses the `iframe` configured in dashboard. It's like in the web SDK. Do you want me to make a pull request or you don't want `iframe` usage for this Javascript SDK ? (I implemented something that work with Ionic app)

**Comment by trinisofttechnologies** [comment]
This is fixed and pushed in current version.

countly.askForFeedback("5e425407975d006a22535fc", "close");

https://support.count.ly/hc/en-us/articles/360037813011-Phonegap-Icenium-Meteor#star-rating-dialog
