### ISSUE TITLE
Implement Compliance Hub functions (GDPR-related)

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#41]
For more information: 

- https://resources.count.ly/docs/compliance-hub
- https://resources.count.ly/docs/sdk-development-guide

**Comment by trinisofttechnologies** [comment]
It is implemented.

Documentation available here:

https://support.count.ly/hc/en-us/articles/360037813011-Phonegap-Icenium-Meteor#user-consent-management
