### ISSUE TITLE
Rich push notifications for iOS

### ISSUE THREAD

**Issue by gorkem-cetin** [Countly/countly-sdk-cordova#42]
Implement rich push notifications for Cordova iOS SDK.

**Comment by gorkem-cetin** [comment]
This one has been implemented in latest SDK.

**Comment by trinisofttechnologies** [comment]
Please review this video for rich push notification for iOS

https://drive.google.com/file/d/1HV1Zm9gHmEigpDp50U6_i_B2cjoQY7Cs/view?usp=sharing
