### ISSUE TITLE
App crash on iOS with sendEvent and segments

### ISSUE THREAD

**Issue by andreialecu** [Countly/countly-sdk-cordova#43]
I'm just implementing this plugin and saw my iOS app hard-crash while calling `Countly.sendEvent`

Upon inspection, I think it is because I didn't have `eventCount` properly defined on the parameter to `sendEvent`. After setting `eventCount` to 1 it stopped crashing.

Relevant lines:
https://github.com/Countly/countly-sdk-js/blob/master/Countly.js#L52
https://github.com/Countly/countly-sdk-js/blob/master/src/ios/CountlyCordova.m#L276

Since `eventCount` is not defined, the whole array is shifted so the iOS routine crashes by assuming an index in the array that doesn't exist.

I think it's safe to just assume `eventCount` to be `1` in Countly.js there if it is not defined.

**Comment by gorkem-cetin** [comment]
Many thanks @andreialecu  - let's check this :-)

**Comment by trinisofttechnologies** [comment]
Yes, I have defaulted it to 1, but I will check it.

**Comment by trinisofttechnologies** [comment]
Yes, defaulted the count to 1, it was missing.

I will have a test example for it, where multiple data type missing, and confirming the sdk doesn't crash.
