### ISSUE TITLE
Don’t register ios users push notification after the update 18.08.1 Ionic 

### ISSUE THREAD

**Issue by khalilbhs** [Countly/countly-sdk-cordova#46]
I integrated the phonegap push and count.ly plugins into my ionic project , I configured the push server and I get the push token . I still have this problem No user can enable push for the specified options 
just for iOS for Android OK .
![sans titre123456](https://user-images.githubusercontent.com/48063667/53506480-58d00f00-3ab6-11e9-87e6-304ca930c7dd.png)

![68065af3cc0fa07d4ed13fc3070ae58936bebf6c](https://user-images.githubusercontent.com/48063667/53506604-946ad900-3ab6-11e9-9cdf-1a73661e158c.png)

**Comment by khalilbhs** [comment]
I had this error message I do know if he can inpact the execution ??
![ioscountly](https://user-images.githubusercontent.com/48063667/53894683-d228ae00-4030-11e9-803d-0462afaadeeb.png)

**Comment by khalilbhs** [comment]
the problem in this function add in the last update is not allowed by ios divice
![fonction](https://user-images.githubusercontent.com/48063667/53959987-5d637b80-40e5-11e9-93ac-26b431e4bb3a.png)
![fonction1](https://user-images.githubusercontent.com/48063667/53960081-98fe4580-40e5-11e9-982e-5ba59db7a65f.png)
which generated this authorization error

![](https://user-images.githubusercontent.com/48063667/53894683-d228ae00-4030-11e9-803d-0462afaadeeb.png)

**Comment by khalilbhs** [comment]
The server (that the POST request is sent to) needs to include the Access-Control-Allow-Headers header (etc) in its response. Putting them in your request from the client has no effect.

This is because it is up to the server to specify that it accepts cross-origin requests (and that it permits the Content-Type request header, and so on) – the client cannot decide for itself that a given server should allow CORS.

**Comment by trinisofttechnologies** [comment]
@khalilbhs 

This is a known issue.

This is reported by another customer.

Now I realize how it is happening.

Will fix it in the next release.

Thanks

**Comment by trinisofttechnologies** [comment]
This issue is fixed in the latest release.

Now it doesn't go through the Ajax process, instead uses the sdk to send token.
