### ISSUE TITLE
Is there a reason for the crash log string length limit?

### ISSUE THREAD

**Issue by be-ndee** [Countly/countly-sdk-cordova#48]
When adding a crash log, the string-length is limited to 1000 chars. Is there a reason for this limit?

```const NSInteger kCountlyCustomCrashLogLengthLimit = 1000;```

**Comment by gorkem-cetin** [comment]
CC @erkanyildiz since it may be related to iOS SDK too.

**Comment by erkanyildiz** [comment]
If I recall correctly, this was a requirement by Countly Server's Crashes section UI.

**Comment by be-ndee** [comment]
Alright, thanks for the answer. I will have a look at server code.

**Comment by trinisofttechnologies** [comment]
Closing this issue, as not active.

Please re open if you think your issue is not resolved.
