### ISSUE TITLE
[Cordova] [iOS] Manually set location does not appear in Countly User Profile

### ISSUE THREAD

**Issue by serpaulius** [Countly/countly-sdk-cordova#49]
Hello,

We are using `Countly.setOptionalParametersForInitialization` function in both Android and iOS and passing _latitude/longitude_ numbers like this:

`{"countryCode":"DK","latitude":56,"longitude":10}`

This works well on Android devices - however, it does not work on iOS devices - the coordinates are saved to Countly user, but they are not resolved to any _country_ and _city_ (both displayed _Unknown_ in the Countly User Profile).

However, when we tried another approach of parsing the numbers to float strings with at least one decimal place, it started working including auto discovery of **both** _country_ and _city_:

`{"countryCode":"DK","latitude":"56.0000","longitude":"10.0000"}`

Most probably there is some conversion issue in the iOS native plugin and/or in the server, which may not understand non-float values when trying to parse the coordinates.

**Possible fixes** - need to include this specific case in Documentation (remind users to pass _float_ strings), or to fix the conversion issues inside plugin/Countly server.

**Comment by trinisofttechnologies** [comment]
Yes that is correct, it requires float value.


Mostly the coordinates are in float.


I will convert the integer value to float in SDK so there is no conversion error.

**Comment by trinisofttechnologies** [comment]
I will fix this in an hour, and update this issue.

Thanks

**Comment by trinisofttechnologies** [comment]
Added padding float value, if integer found.

https://github.com/Countly/countly-sdk-js/commit/0bc7e877329c2aa0349d69a16ac7517e7134fb1f

There is the fix.

**Comment by serpaulius** [comment]
Thank you!
