### ISSUE TITLE
Capacitor Support?

### ISSUE THREAD

**Issue by ingageco** [Countly/countly-sdk-cordova#55]
Any chance this supports Capacitor apps?

**Comment by nicolsondsouza** [comment]
Yes, Capacitor does support Cordova plugin.

I will update this thread to inform you if it is also supported in capacitor as well.

**Comment by ingageco** [comment]
Not every Cordova plugin works with Capacitor - just asking to see if the Countly JS Cordova plugin had been specifically tested on Capacitor?

Thank you for the response!

**Comment by trinisofttechnologies** [comment]
Hi @ingageco 

Unfortunately, it doesn't support capacitor.

As it has a different architecture than cordova.

It has to be written from scratch, 

I will check with my superior,

If we want to make a bridge for it.

Thanks

**Comment by trinisofttechnologies** [comment]
@ingageco 

At the moment, we don't have any plan to support capacitor.

But in the future based on the popularity of the framework we may decide to create one.

I will close the issue now.

Thanks
