### ISSUE TITLE
 error: cannot find symbol onRegistrationId

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-cordova#6]
On android I am getting the error

cordova/platforms/android/src/ly/count/android/api/CountlyCordova.java:121:Countly.sharedInstance().onRegistrationId(registrationId);

The method onRegistrationId(String) is undefined for the type Countly

**Comment by nicolsondsouza** [comment]
ok working on it.

**Comment by nicolsondsouza** [comment]
can you see check with the latest pull,
this is working fine for me.

**Comment by nicolsondsouza** [comment]
As per the latest pull, 
this is now resolved.
closing this issue.

**Comment by deliriousrhino** [comment]
Thanks @nicolsondsouza This was the case
