### ISSUE TITLE
google-services.json requirement

### ISSUE THREAD

**Issue by adammeyer** [Countly/countly-sdk-cordova#60]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
```

Getting this error when building my app.  I understand this is required if you want to use Android push notifications, but what if I just want to capture analytics, how can this error be resolved?

Thanks

**Comment by JuanVanH** [comment]
Having the same issue

**Comment by ArtursKadikis** [comment]
Hello, yes it's required for using push notifications on android. If you would want to remove it, you would have to do these steps for Cordova:
* go into "plugins" folder
* open "fetch.json" and remove entry for "cordova-support-google-services"
* open  "android.json" and remove entry for "cordova-support-google-services"
* delete "cordova-support-google-services" folder
* go into our SDK folder in the plugins folder
* open "plugin.xml" and remove lines from the android push notification section, EXCEPT this one:
`<framework src="com.google.firebase:firebase-messaging:20.0.0" />`

Like this:
https://github.com/Countly/countly-sdk-cordova/blob/master/plugin.xml#L92-L100

And this:
https://github.com/Countly/countly-sdk-cordova/blob/master/plugin.xml#L102
