### ISSUE TITLE
Android Segment Only sends first item in segment

### ISSUE THREAD

**Issue by deliriousrhino** [Countly/countly-sdk-cordova#7]
I noticed that on android I was only getting the first segment.

I think the problem is in the loop in CountlyCordova.java

```
for(int i=3,il=5;i<il;i+=2){
```

should be

```
for(int i=3,il=args.length();i<il;i+=2){
```

**Comment by nicolsondsouza** [comment]
ok checking.

**Comment by nicolsondsouza** [comment]
Fixed,
I was testing so I put 5, now should be good.
