### ISSUE TITLE
how can i used sdk for cocos2d-js?

### ISSUE THREAD

**Issue by shadow0162** [Countly/countly-sdk-cordova#8]
Ii'm a game developer. i used cocos2d game engine to develop products.
it's a way to use sdk in cocos2d-js version?

**Comment by derekmoorecountly** [comment]
Currently we do not have an SDK for cocos2d-js.

**Comment by shadow0162** [comment]
So sad

**Comment by shadow0162** [comment]
I try to port an SDK on cocos2d-js.

**Comment by ar2rsawseen** [comment]
Then you would need to implement HTTP call with parameters from this page:
http://resources.count.ly/v1.0/docs/i

**Comment by shadow0162** [comment]
I finished th cocos2d-x for countly sdk version.
https://github.com/shadow0162/countly-sdk-cocos2d-x

Any questions, please feel free to contact me

**Comment by trinisofttechnologies** [comment]
@gorkem-cetin 

Please look at this issue, and take appropriate action.

This doesn't look like an issue, from the last comment.

Closing it.

Please re-open, if you think the problem persists.

Thanks
