### ISSUE TITLE
I got an error when add this plugin to my project

### ISSUE THREAD

**Issue by kyugao** [Countly/countly-sdk-cordova#9]
D:\src_workspace\MyApp>cordova plugin add https://github.com/Countly/countly-sdk-js.git
Fetching plugin "https://github.com/Countly/countly-sdk-js.git" via git clone
Repository "https://github.com/Countly/countly-sdk-js.git" checked out to git ref "master".
shell.js: internal error
Error: EXDEV, cross-device link not permitted 'C:\Users\LANSIO~1\AppData\Local\Temp\git\1435130284828\Countly.js'
    at Error (native)
    at Object.fs.renameSync (fs.js:636:18)
    at C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:77:8
    at Array.forEach (native)
    at Object._mv (C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\mv.js:53:11)
    at Object.mv (C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\node_modules\shelljs\src\common.js:186:23)
    at C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\plugins.js:53:19
    at _fulfilled (C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Lansion08\AppData\Roaming\npm\node_modules\cordova\node_modules\q\q.js:749:13)

**Comment by trinisofttechnologies** [comment]
Hi, I believe this error isn't related to countly, but should be because of npm or nodejs 
you may look here
http://stackoverflow.com/questions/12196163/node-js-fs-rename-doesnt-work

**Comment by trinisofttechnologies** [comment]
$ npm install -g cordova
npm WARN engine cordova-js@4.0.0: wanted: {"node":"~0.10.x"} (current: {"node":"
0.12.2","npm":"2.7.4"})
npm WARN engine npm@1.3.4: wanted: {"node":">=0.6","npm":"1"} (current: {"node":
"0.12.2","npm":"2.7.4"})
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {
"node":"0.12.2","npm":"2.7.4"})
npm WARN installMany normalize-package-data was bundled with npm@1.3.4, but bund
led package wasn't found in unpacked tree
C:\Users\trinisoft\AppData\Roaming\npm\cordova -> C:\Users\trinisoft\AppData\Roa
ming\npm\node_modules\cordova\bin\cordova
cordova@5.1.1 C:\Users\trinisoft\AppData\Roaming\npm\node_modules\cordova
├── underscore@1.7.0
├── q@1.0.1
├── nopt@3.0.1 (abbrev@1.0.7)
└── cordova-lib@5.1.1 (valid-identifier@0.0.1, osenv@0.1.0, properties-parser@0.
2.3, bplist-parser@0.0.6, mime@1.2.11, unorm@1.3.3, semver@2.1.0, shelljs@0.3.0,
 cordova-app-hello-world@3.9.0, rc@0.5.2, npmconf@0.1.16, dep-graph@1.1.0, xcode
@0.6.7, elementtree@0.1.6, through2@0.6.3, glob@4.0.6, cordova-registry-mapper@1
.1.8, npm@1.3.4, request@2.47.0, plist@1.1.0, tar@1.0.2, init-package-json@1.7.0
, d8@0.4.4, cordova-js@4.0.0)

trinisoft@TRINISOFT-PC ~
$ cd office/

trinisoft@TRINISOFT-PC ~/office
$ mkdir cordova

trinisoft@TRINISOFT-PC ~/office
$ cd cordova/

trinisoft@TRINISOFT-PC ~/office/cordova
$ ls

trinisoft@TRINISOFT-PC ~/office/cordova
$ cordova create CountlyDemo ly.count.demo CountlyDemo
Creating a new cordova project.

trinisoft@TRINISOFT-PC ~/office/cordova
$ cd CountlyDemo/

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$ ls
config.xml  hooks  platforms  plugins  www

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$  cordova plugin add org.apache.cordova.device
WARNING: org.apache.cordova.device has been renamed to cordova-plugin-device. Yo
u may not be getting the latest version! We suggest you `cordova plugin rm org.a
pache.cordova.device` and `cordova plugin add cordova-plugin-device`.
Fetching plugin "org.apache.cordova.device" via cordova plugins registry
npm http GET http://registry.cordova.io/org.apache.cordova.device
npm http 200 http://registry.cordova.io/org.apache.cordova.device
npm http GET http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apac
he.cordova.device/-/org.apache.cordova.device-0.3.0.tgz
npm http 200 http://cordova.iriscouch.com/registry/_design/app/_rewrite/org.apac
he.cordova.device/-/org.apache.cordova.device-0.3.0.tgz

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$ cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone

Repository "https://github.com/phonegap-build/PushPlugin.git" checked out to git
 ref "master".

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$ cordova plugin add https://github.com/Countly/countly-sdk-js.git
Fetching plugin "https://github.com/Countly/countly-sdk-js.git" via git clone
Repository "https://github.com/Countly/countly-sdk-js.git" checked out to git re
f "master".

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$ cordova platform add android
npm http GET https://registry.npmjs.org/cordova-android
npm http 200 https://registry.npmjs.org/cordova-android
npm http GET https://registry.npmjs.org/cordova-android
npm http 200 https://registry.npmjs.org/cordova-android
npm http GET https://registry.npmjs.org/cordova-android/-/cordova-android-4.0.2.
tgz
npm http 200 https://registry.npmjs.org/cordova-android/-/cordova-android-4.0.2.
tgz
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: ly.count.demo
        Name: CountlyDemo
        Activity: MainActivity
        Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.2
Discovered plugin "cordova-plugin-whitelist" in config.xml. Installing to the pr
oject
Fetching plugin "cordova-plugin-whitelist@1" via npm
npm http GET https://registry.npmjs.org/cordova-plugin-whitelist
npm http 200 https://registry.npmjs.org/cordova-plugin-whitelist
npm http GET https://registry.npmjs.org/cordova-plugin-whitelist/-/cordova-plugi
n-whitelist-1.1.0.tgz
npm http 200 https://registry.npmjs.org/cordova-plugin-whitelist/-/cordova-plugi
n-whitelist-1.1.0.tgz
Installing "cordova-plugin-whitelist" for android
Installing "com.phonegap.plugins.PushPlugin" for android
Installing "ly.count.cordova" for android
Installing "org.apache.cordova.device" for android

trinisoft@TRINISOFT-PC ~/office/cordova/CountlyDemo
$

This is a fresh installation for windows, from strach.

**Comment by trinisofttechnologies** [comment]
Let me know if this helps your question, so that I can close this issue.
Thanks

**Comment by nicolsondsouza** [comment]
@kyugao  closing this issue, as not found bug in countly sdk,
please reopen again, if you are still facing issue with integrating the sdk
